// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8FFAb_CZkgls2gI5VuhlwGITZhNZV-M',
    appId: '1:938388279821:android:6649c4f91b9112cf6ffb44',
    messagingSenderId: '938388279821',
    projectId: 'uogguide-b00c8',
    storageBucket: 'uogguide-b00c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ltBhcPQUX7uewBlFomGlNSKOJLtJdzM',
    appId: '1:938388279821:ios:51af30de7a1120a66ffb44',
    messagingSenderId: '938388279821',
    projectId: 'uogguide-b00c8',
    storageBucket: 'uogguide-b00c8.firebasestorage.app',
    iosBundleId: 'com.uogguide.uogGuide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAde4fB5vq6eFFjGg74-Z2JnchF36H3lSY',
    appId: '1:938388279821:web:0fb8fdd7c26eb0566ffb44',
    messagingSenderId: '938388279821',
    projectId: 'uogguide-b00c8',
    authDomain: 'uogguide-b00c8.firebaseapp.com',
    storageBucket: 'uogguide-b00c8.firebasestorage.app',
  );

}